---
title: "SOnarLCA"
author: "Jose Tamez"
date: "5/16/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("FRESA.CAD")
library(epiR)
library(clValid)
library(mclust)

source('~/GitHub/EvalCluster/R/clusterStability.r')


```

## The cluter wrappers for HLCM_EM
```{r}
latentClass <- function(data,formula,...)
{
  HLCM_EMM <- HLCM_EM(formula,data,...);
  result <- list(model=HLCM_EMM )
  class(result) <- "latentClass"
  return (result)
}

predict.latentClass <- function(model,data)
{
  testResult <-  predict(model$model,data)
  latentclass <- apply(attr(testResult,"probabilities"),1,which.max)
  result <- list(classification = 2*latentclass + 1*(testResult >= 0.5),outcome=testResult,latentclass=latentclass)
#  result <- list(classification = latentclass,outcome=testResult,latentclass=latentclass)
  return(result)
}

```



## Sonar Data Set

Loading the data from the mlbech package.

```{r FRESA Map, results = "hide", dpi=300, fig.height= 6.0, fig.width= 8.0}
data(Sonar, package = "mlbench")
Sonar$Class <- 1*(Sonar$Class == "M")
table(Sonar$Class)

```


## Check performance
```{r}

LASSOSVM <- latentClass(Sonar,
              formula = Class ~ .,
              hysteresis = 0.10,
              method=LASSO_1SE,
               classMethod=e1071::svm,
              classModel.Control=list(probability = TRUE),
              family="binomial")

prd <- predict(LASSOSVM,Sonar)
testTable <- table(prd$outcome<0.5,Sonar$Class==0)
epi.tests(testTable)

BSWiMSVM <- latentClass(Sonar,
              formula = Class ~ .,
              hysteresis = 0.10,
              method=BSWiMS.model,
               classMethod=e1071::svm,
              classModel.Control=list(probability = TRUE),
              )

prd <- predict(BSWiMSVM,Sonar)
testTable <- table(prd$outcome<0.5,Sonar$Class==0)
epi.tests(testTable)


```



## Targeted Clustering

```{r}
#clsta <- clusterStability(data=Sonar, 
#                          clustermethod=latentClass,
#                          randomTests = 200, 
#                          trainFraction = 0.75,
#                          formula = Class ~ .,
#                          hysteresis = 0.10,
#                          method=LASSO_1SE,
#                           classMethod=e1071::svm,
#                          classModel.Control=list(probability = TRUE),
#                          family="binomial")

```

## Targeted Clustering LCA BSWiMS

```{r}

#clsta <- clusterStability(data=Sonar, 
#                          clustermethod=latentClass,
#                          randomTests = 200, 
#                          trainFraction = 0.75,
#                          formula = Class ~ .,
#                          hysteresis = 0.10,
#                          method=BSWiMS.model,
#                           classMethod=e1071::svm,
#                          classModel.Control=list(probability = TRUE)
#                          )
#save(clsta,file="BSWIMS_SVM.RDATA")

load(file="BSWIMS_SVM.RDATA")



```



## Get the consensus clusers

```{r}

#ccluster <- getConsensusCluster(clsta,who="testing",thr=seq(0.60,0.30,-0.05))
#ccluster <- getConsensusCluster(clsta,who="testing")
#ccluster <- getConsensusCluster(clsta,thr=seq(0.60,0.30,-0.05))
ccluster <- getConsensusCluster(clsta)
table(ccluster,Sonar$Class)
#testTable <- table(ccluster == 4  | ccluster == 8,Sonar$Class==0)
#epi.tests(testTable)



#rclass <- relaxConsensusCluster(clsta,ccluster,ww=13,loops=21);
rclass <- relaxConsensusCluster(clsta,ccluster);
table(ccluster,rclass)
table(rclass,Sonar$Class)

```


## Review the consensus maps

```{r}
mycolors <- c("red","green","blue","yellow","cyan","pink","black","gray","violet","orange","brown")
rowcolors <- mycolors[1+ccluster]

orderindex <- 10*ccluster - clsta$trainJaccardpoint

ordermatrix <- clsta$dataConcensus[order(-orderindex),order(orderindex)]
#ordermatrix <- clsta$testConsesus[order(-orderindex),order(-orderindex)]
ccolcolors <- rowcolors[order(orderindex)]
crowcolors <- rowcolors[order(-orderindex)]

hplot <- gplots::heatmap.2(as.matrix(ordermatrix),
                           Rowv=FALSE,
                           Colv=FALSE,
                           RowSideColors = crowcolors ,
                           ColSideColors = ccolcolors ,
                           dendrogram = "none",
                           trace="none",
                           main="Cluster Co-Association")

rowcolors <- mycolors[1+rclass]

orderindex <- 10*rclass - clsta$trainJaccardpoint

#ordermatrix <- clsta$testConsesus[order(-orderindex),order(-orderindex)]
ordermatrix <- clsta$dataConcensus[order(-orderindex),order(orderindex)]
ccolcolors <- rowcolors[order(orderindex)]
crowcolors <- rowcolors[order(-orderindex)]

hplot <- gplots::heatmap.2(as.matrix(ordermatrix),
                           Rowv=FALSE,
                           Colv=FALSE,
                           RowSideColors = crowcolors ,
                           ColSideColors = ccolcolors ,
                           dendrogram = "none",
                           trace="none",
                           main="Cluster Co-Association")


hplot <- gplots::heatmap.2(as.matrix(clsta$dataConcensus),
                           RowSideColors = rowcolors ,
                           ColSideColors = rowcolors ,
                           trace="none",
                           main="Cluster Co-Association")


#hplot <- gplots::heatmap.2(as.matrix(clsta$testConsesus),
#                           RowSideColors = rowcolors ,
#                           ColSideColors = rowcolors ,
#                           trace="none",
#                           main="Cluster Co-Association")

```

## Analyze the clusters

```{r}

subsetClass1 <- subset(Sonar[,BSWiMSVM$model$selectedfeatures],ccluster==1)
subsetClass2 <- subset(Sonar[,BSWiMSVM$model$selectedfeatures],ccluster==2)
subsetClass3 <- subset(Sonar[,BSWiMSVM$model$selectedfeatures],ccluster==3)
signature1 <- colMeans(subsetClass1)
signature2 <- colMeans(subsetClass2)
signature3 <- colMeans(subsetClass3)
orders <- order(signature1)
boxplot(Sonar[,BSWiMSVM$model$selectedfeatures[orders]],lty=1,main="Sonar Signatures",xlab="Feature",ylab="Sonar",las=2)
lines(signature1[orders],col="green")
lines(signature2[orders],col="blue")
lines(signature3[orders],col="red")
legend("topleft",
           legend = c("Class 1 (Mines)","Class 2 (Rocks)","Class 3 (Rocks)"),
           col = c("green","blue","red"),
           lty = c(1,1,1),
           lwd = c(1,1,1),
           cex=0.5)


```

